### ISSUE TITLE
Isuee with ordinal followed by cardinal

### ISSUE THREAD

**Issue by fersarr** [ShailChoksi/text2digits#38]
Currently `'second one'` gets converted into `'21'`

```
>>> t2d = text2digits.Text2Digits()
>>> t2d.convert('Those were my friends. Particularly the second one there')
'Those were my friends. Particularly the 21 there'
```

Should be:

```
>>> t2d.convert('Those were my friends. Particularly the second one there')
'Those were my friends. Particularly the 2nd 1 there'
```

Additionally, when using the ordinals params it crashes:
```
>>> t2d = text2digits.Text2Digits(convert_ordinals=True, add_ordinal_ending=True)
>>> t2d.convert('Those were my friends. Particularly the second one there')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fersarr/miniconda2/envs/feedbak/lib/python3.8/site-packages/text2digits/text2digits.py", line 51, in convert
    text = self._parse(tokens)
  File "/Users/fersarr/miniconda2/envs/feedbak/lib/python3.8/site-packages/text2digits/text2digits.py", line 130, in _parse
    text += token.ordinal_ending
TypeError: can only concatenate str (not "NoneType") to str
```

versions:
```
text2digits-0.1.0
python 3.8.5
```

**Comment by fersarr** [comment]
added  PR to fix

**Comment by ShailChoksi** [comment]
Fixed in v0.1.2
