### ISSUE TITLE
first one number -> error!

### ISSUE THREAD

**Issue by gusrud1103** [ShailChoksi/text2digits#45]
Hello. When ```first one number``` is existed in a sentence, it results this error.
```
token =  11
token.ordinal_ending =  None

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/text2digits/text2digits.py", line 51, in convert
    text = self._parse(tokens)
  File "/usr/local/lib/python3.6/dist-packages/text2digits/text2digits.py", line 133, in _parse
    text += token.ordinal_ending
TypeError: must be str, not NoneType
```

**Comment by gusrud1103** [comment]
It is solved by updating version of package.
